# Generated by Django 4.1.5 on 2023-01-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
