# Generated by Django 4.1.5 on 2023-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0004_alter_student_mobile_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Data_of_birth',
            field=models.TextField(),
        ),
    ]
