# Generated by Django 4.1.5 on 2023-01-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0005_alter_student_data_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Data_of_birth',
            field=models.DateField(),
        ),
    ]
