# Generated by Django 4.1.5 on 2023-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0006_alter_student_data_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Django', 'Django'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Full Stack Web Development', 'Full Stack Web Development'), ('C Programming', 'C Programming')], max_length=100),
        ),
    ]
