# Generated by Django 4.1.3 on 2023-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0007_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Django', 'Django'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science in Python'), ('Machine Learning', 'Machine Learning'), ('Full Stack Web Development', 'Full Stack Web Development'), ('C Programming', 'C Programming')], max_length=100),
        ),
    ]
