# Generated by Django 4.1.3 on 2023-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0008_remove_student_father_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Data_of_birth',
            new_name='Date_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Django', 'Django'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science in Python'), ('Machine Learning', 'Machine Learning'), ('Full Stack Web Development', 'Full Stack Web Development'), ('C Programming', 'C Programming'), ('DataBase', 'DataBase')], max_length=100),
        ),
    ]
