# Generated by Django 4.1.5 on 2023-01-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aruviapp', '0009_rename_data_of_birth_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
